# serverless.yml

service: my-express-application

custom:
  campTableName: 'camp-table-${self:provider.stage}'
  tableName: 'users-table-${self:provider.stage}'
  dynamodb:
    start:
      migrate: true
 

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["UsersDynamoDBTable","Arn" ] }
        - { "Fn::GetAtt": ["CampaignDynamoDBTable","Arn" ] }
  environment:
    USERS_TABLE: ${self:custom.tableName}
    CAMP_TABLE: ${self:custom.campTableName}

functions:
  app:
    handler: index.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
  getUser:
    handler: index.handler
    events:
      - http: 'GET /users/{proxy+}'
  createUser:
    handler: index.handler
    events:
      - http: 'POST /users'


resources:
  Resources:
      CampaignDynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          AttributeDefinitions:
            -
              AttributeName: campaignId
              AttributeType: S
          KeySchema:
            -
              AttributeName: campaignId
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          TableName: ${self:custom.campTableName}
  
      UsersDynamoDBTable:
        Type: 'AWS::DynamoDB::Table'
        Properties:
          AttributeDefinitions:
            -
              AttributeName: userId
              AttributeType: S
          KeySchema:
            -
              AttributeName: userId
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
          TableName: ${self:custom.tableName}


plugins:
  - serverless-dynamodb-local
  - serverless-offline #serverless-offline needs to be last in the list
